[build]
  command = "parcel build index.html"
  publish = "/dist"
   url = "https://github.com/Sreelesh-a/fud-spot.  refs/heads/main"

   [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
